### ISSUE TITLE
As a user, I want to filter my journal to a given time period

### ISSUE THREAD

**Issue by MGZero** [mvegh1/DiFractal#150]
-There should be a dropdown at the top of the journal allowing the user to select different time periods for the journal
-the options should be as follows:
   -Current Year
   -Last six months
   -Date range
   -Year range
   -All
-The default option should be current year
-Year range should provide two text boxes that the user can enter a start and end year
-Date range should provide two datepickers that the user can enter a start and end date

**Comment by mvegh1** [comment]
Generally this is fine, but I do have an implementation remark to make.

The backend will accept a RangeFilter<DateTime> object (which has a Specific property. Which we dont need to have for journal querying).

If you are not going to implement behavior (syncing the back and front end) then nothing for you to worry about. I can handle the behavior aspect. Otherwise, just something to keep in mind.

Also. I want a more comprehensive search feature for the journal. I need to edit this spec with what the search should entail. But, having RangeFilters on Bodyweight,Energy,Rating are 3 additional ones I was thinking. Then, being able to filter by Workout Type and Exercise via MultiSelect Typeaheads is 2 more. But, then I think being able to drill down at the exercise level (i.e find all workouts where Squat was performed, constrained by RangeFilter for reps, weight, rep)

Maybe even being able to filter by Comments, and/or ExerciseComments is useful too
