### ISSUE TITLE
As a user, I want to add exercises to my workout

### ISSUE THREAD

**Issue by MGZero** [mvegh1/DiFractal#153]
-The exercises tab of the add workout should use an accordion interface in a similar way to the journal
-Clicking the add button will add a new accordion section to the top of the collection
-Accordions will default to open
-Each accordion will have the following fields:
   1. Weight - a number picker (required - can be 0)
   2. Radio buttons indicating the type of sets (time vs reps) - This only shows for new exercises
   3. Sets - a number picker (required - must be greater than 0)
   4. Time - a duration picker indicating the number of seconds the set lasted for (only visible if time radio button is selected - Required - must be greater than 0s) 
   5. Reps - a number picker indicating the number of reps per set (only visible if reps radio button is selected - required - must be greater than 0)
   6. RPE - a bootstrap 10 star rating
   7. Comments

**Comment by mvegh1** [comment]
Is "time" (#4) new? Most, if not all, weight lifters dont time how long a
set took.

HOWEVER, if you mean something like how we do static holds, like the L-Sit,
then yes, I agree a UI interface for that can be good.

Once you answer that question, we could discuss how this plays with the
database model.

**Comment by MGZero** [comment]
Yes, it's for static holds hence the radio button

**Comment by mvegh1** [comment]
How did you envision the database model?

**Comment by MGZero** [comment]
Can you post the current model for an exercise so I can reference it?

**Comment by mvegh1** [comment]
It's in DiFractal.Workout.Database/Models/WorkoutItem.cs

**Comment by MGZero** [comment]
We can just add two new fields to support it:
a timespan for the actual time
an integer to drive the radio button

**Comment by mvegh1** [comment]
By integer do you mean a lookup value? i.e ExerciseProtocolId (for
arguments sake, im not sure of a good name now).

So we would have another table, ExerciseProtocol(Id,Name) {  {
{{Id}},"Standard" }, { {{Id}}, "Isometric" } },

And then WorkoutItem would hold an ExerciseProtocolId value, and another
column Duration as Timespan?

**Comment by mvegh1** [comment]
Remember, we use Guids for Ids here, not integers

**Comment by MGZero** [comment]
Yup, a lookup is what I mean, and yea thats what WorkoutItem would have

**Comment by mvegh1** [comment]
Sounds good to me! Any ideas for names of the lookup values, and the table?
I'm not sure if protocol is ambiguous here. Or. Perhaps it is fine, and the
entries could simply be [Repetition,Timed]

**Comment by mvegh1** [comment]
After speaking with MGZero, we will only let the user Toggle for NEW
exercises. There is an Entity level method in front end  called IsNew(), so
you could do Exercise.IsNew() to determine if you should show the toggle.
Else, I suppose you could assume there will be some sort of property that
let's you know the value of the toggle. You can fake that for now :)

**Comment by mvegh1** [comment]
Update: We will store the Time in the Reps field, and UserExercise table will have another column Protocol (or w.e) storing Repetition or Timed. That will be configured when a user adds a new exercise. A user currently adds a new Exercise via the Add-Workout form, and to detect if an Exercise is new, all you would have to do is call WorkoutEntry.Exercise.IsNew(). Then, if it is new, show the toggle to choose between Timed or Repetition. I think our SegmentPicker makes sense here for that (see Export or Settings page for how thats used). Otherwise, dont show toggle, because the server already knows what the value of the toggle is in the database

**Comment by mvegh1** [comment]
Update to most recent comment: We removed Protocol entirely, and now there is nullable Time (int) = seconds on WorkoutItem table

**Comment by mvegh1** [comment]
After thinking about it, I have a proposal for how the Add-Workout form > Exercises Tab looks and feel

So, I like the general gist of how the journal shows the exercises. Now, as a reminder, when you're viewing your journal and you hit the edit button, it initializes an Add-Workout form right there and you have the option to save or cancel your changes.

Running with that idea, we can use a similar "view" in the exercises tab that mimicks how it looks in the journal, and use similar edit/delete buttons to perform actions. Clicking edit icon would activate a form in place that lets you modify that exercise, and when edit is complete it goes back to just regular text

Thoughts, @MGZero ? 

Once we reach an agreement on look/feel, we should decide who will implement that change., It isn't much of a lift, since all of the code for both views exists, but there will definitely be template changes AND component.ts changes
